name: Android CI

on:
  push: # Run on ANY branch push
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Gradle initialization script for dependency fixes
        run: |
          cat > init.gradle << 'EOL'
          allprojects {
              repositories {
                  mavenCentral()
                  google()
              }
          
              configurations.all {
                  resolutionStrategy.force 'com.squareup:javapoet:1.13.0'
                  resolutionStrategy.force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.0'
                  resolutionStrategy.force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0'
              }
          }
          EOL

      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches/
          ./gradlew clean

      - name: Build with Gradle using init script
        run: ./gradlew --init-script init.gradle build --stacktrace --info

      - name: Build Debug APK (even if tests fail)
        if: always()
        run: ./gradlew --init-script init.gradle assembleDebug --stacktrace

      - name: Upload APK
        if: always()  # Try to upload even if previous steps failed
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            app/build/reports/
            **/build/reports/
            app/build/outputs/logs/
